### ISSUE TITLE
Thor repository in first time run

### ISSUE THREAD

**Issue by lscheffler** [VFPX/ThorNews#11]
## 📝 Provide a description of the new feature

For a first time run of Thor, CFU marks PEM Editor as suggestion to install.   
Since *Thor Repository* is a major part. I think it should be marked too. There where issues on the site formerly known as UniversalThread about this.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Jimrnelson** [comment]
This issue was taken care of by a change in Thor, using the new .Dependencies property.
